--SELECT DO INTEGRADOR DE PEDIDOS
--SELECT * FROM MQ_ECATALOGOS_ESTOQUE_CONTROL

--SELECT LOG DO INTEGRADOR
--SELECT * FROM MQ_LOG_INTEGRACAO_ECATALOGOS_LOJAS WHERE MODULO = 'PEDIDOS_LOJA' ORDER BY DATA_INTEGRACAO DESC


SELECT TOP(50) 
	ID
	,STATUS
	,DATA_INTEGRACAO
	,MODULO
	,CHAVE
	,ACAO
	,ERRO
	,JSON_ERRO
	,USUARIO
	,JSON_ENVIADO
FROM MQ_LOG_INTEGRACAO_ECATALOGOS_LOJAS 
	--WHERE MODULO = 'PEDIDOS_LOJA' 
ORDER BY DATA_INTEGRACAO DESC
