SELECT    produtos_packs_permitidos.produto,
          produtos_packs_permitidos.qtde,
          produtos_packs_permitidos.pack,
          produtos_packs_permitidos.cor_produto,
          produtos_packs_permitidos.indica_pack_cor,
          produtos_packs_permitidos.inativo,
          produto_cores.desc_cor_produto,
          produtos_packs_permitidos.q1,
          produtos_packs_permitidos.q2,
          produtos_packs_permitidos.q3,
          produtos_packs_permitidos.q4,
          produtos_packs_permitidos.q5,
          produtos_packs_permitidos.q6,
          produtos_packs_permitidos.q7,
          produtos_packs_permitidos.q8,
          produtos_packs_permitidos.q9,
          produtos_packs_permitidos.q10,
          produtos_packs_permitidos.q11,
          produtos_packs_permitidos.q12,
          produtos_packs_permitidos.q13,
          produtos_packs_permitidos.q14,
          produtos_packs_permitidos.q15,
          produtos_packs_permitidos.q16,
          0 AS q17,
          0 AS q18,
          0 AS q19,
          0 AS q20,
          0 AS q21,
          0 AS q22,
          0 AS q23,
          0 AS q24,
          0 AS q25,
          0 AS q26,
          0 AS q27,
          0 AS q28,
          0 AS q29,
          0 AS q30,
          0 AS q31,
          0 AS q32,
          0 AS q33,
          0 AS q34,
          0 AS q35,
          0 AS q36,
          0 AS q37,
          0 AS q38,
          0 AS q39,
          0 AS q40,
          0 AS q41,
          0 AS q42,
          0 AS q43,
          0 AS q44,
          0 AS q45,
          0 AS q46,
          0 AS q47,
          0 AS q48
FROM      produtos_packs_permitidos
LEFT JOIN produto_cores
ON        produtos_packs_permitidos.produto = produto_cores.produto
AND       produtos_packs_permitidos.cor_produto = produto_cores.cor_produto
WHERE     produtos_packs_permitidos.produto = '19.64.0047'
