--Script de Consulta de Clientes Utilizado no Integrador
--Os campos deste select são os campos obrigatórios a serem preenchidos no cadastro de clientes do Linx para que suba o cliente para o eCatalogo

SELECT DISTINCT 
B.RAZAO_SOCIAL    								AS NAME,
B.NOME_CLIFOR									AS TRADING_NAME,
B.EMAIL											AS MAIL,
B.DDD1 + ' ' + B.TELEFONE1						AS PHONE,
B.COD_CLIFOR									AS CODE,
B.CGC_CPF										AS CNPJ,
CASE WHEN B.INATIVO = 1 THEN 0 ELSE 1 END		AS ATIVO,
E.TIPO_BLOQUEIO,
CASE WHEN E.SEM_CREDITO = 1 THEN 0 ELSE 1 END	AS HAVE_CEDIT,
E.LIMITE_CREDITO,
E.BLOQUEIO_EXPEDICAO,
E.BLOQUEIO_PEDIDOS,
E.BLOQUEIO_FATURAMENTO,
D.ID,
B.NOME_CLIFOR,
D.ACAO,
B.ENDERECO,
B.CIDADE,
B.UF,
B.BAIRRO,
B.NUMERO,
B.CEP,
B.DDD1,
B.TELEFONE1,
B.DDD2,
B.TELEFONE2,
B.DDDFAX,
B.FAX
FROM   MQ_CLIENTE_VENDEDOR AS A
INNER JOIN CLIENTES_ATACADO AS F
ON A.CLIENTE_ATACADO = F.CLIENTE_ATACADO
INNER JOIN CADASTRO_CLI_FOR AS B
ON A.CLIENTE_ATACADO = B.NOME_CLIFOR
INNER JOIN LOJA_VENDEDORES AS C
ON A.VENDEDOR = LTRIM(RTRIM(C.VENDEDOR))
INNER JOIN MQ_INTEGRACAO_ECATALOGOS_LOJAS AS D
ON B.CLIFOR = D.CHAVE
INNER JOIN CLIENTES_ATACADO AS E
ON B.COD_CLIFOR = E.CLIFOR
WHERE  B.INATIVO = 0
AND  D.MODULO = 'CLIENTES_PRIORITY'
AND  F.eCatalogosLoja = 1
