-- Consulta de transportadoras
-- Destacando as transportadoras que constam na tabela de FATURAMENTO e VENDAS

select
 F.NOME_CLIFOR
,V.CLIENTE_ATACADO
,V.PEDIDO
,V.PEDIDO_EXTERNO
,F.NF_SAIDA
,F.SERIE_NF
,F.NATUREZA_SAIDA
,F.FILIAL
--TRANSPORTADORA DA TABELA FATURAMENTO
,F.TRANSPORTADORA AS F_TRANSPORTADORA
,T.COD_MUNICIPIO_IBGE AS F_TRANSP_COD_IBGE
--TRANSPORTADORA DA TABELA VENDAS
,V.TRANSPORTADORA AS V_TRANSPORTADORA
,T2.COD_MUNICIPIO_IBGE AS V_TRANSP_COD_IBGE
,F.EMISSAO
,F.DATA_SAIDA
,F.QTDE_TOTAL
,F.MPADRAO_VALOR_SUB_ITENS
,F.MPADRAO_DESCONTO
,F.MPADRAO_VALOR_TOTAL
,F.VALOR_TOTAL
,F.MPADRAO_FRETE
,F.OBS
FROM 
	TRANSPORTADORAS T --TRANSPORTADORA DA TABELA FATURAMENTO
		INNER JOIN FATURAMENTO F
			ON F.TRANSPORTADORA = T.TRANSPORTADORA
		INNER JOIN VENDAS V
			ON F.NOME_CLIFOR = V.CLIENTE_ATACADO
		INNER JOIN TRANSPORTADORAS T2 --TRANSPORTADORA DA TABELA VENDAS
			ON V.TRANSPORTADORA = T2.TRANSPORTADORA
WHERE
F.TRANSPORTADORA IN ('PROPRIO','PROPRIA  P C DESTINATARIO','B R A EXPRESS')
AND F.EMISSAO BETWEEN '20250101' AND '20251231'
AND V.PEDIDO_EXTERNO LIKE 'LJ%'
order by emissao desc

--select TRANSPORTADORA, * from faturamento where nf_saida = '004399         ' and nome_clifor = 'ELES NO ESTILO           '
--select TRANSPORTADORA, * from vendas where pedido_externo = 'LJ00000740  '
