--Consulta fila para integração
SELECT * FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS
WHERE CHAVE IN (
		'87.09.0257'
	)

--Por Produto
SELECT * FROM MQ_LOG_INTEGRACAO_eCATALOGOS_LOJAS
WHERE MODULO = 'PRODUTOS'
AND CHAVE IN (
		'87.09.0257'
	)
AND DATA_INTEGRACAO >= '20250430'
order by 3 desc, 5 asc
