--Consulta fila para integração
SELECT * FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS
WHERE CHAVE IN (
		'87.09.0257'
	)

--Por Produto
SELECT * FROM MQ_LOG_INTEGRACAO_eCATALOGOS_LOJAS
WHERE MODULO = 'PRODUTOS'
AND CHAVE IN (
		'87.09.0257'
	)
AND DATA_INTEGRACAO >= '20250430'
order by 3 desc, 5 asc


/*

--Consulta fila para integração
SELECT * FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS
WHERE
MODULO IN ('PEDIDO_VENDAS')
AND CHAVE IN (
		'LJ00000448','LJ00000651'
	)

--Por Produto
SELECT * FROM MQ_LOG_INTEGRACAO_eCATALOGOS_LOJAS
WHERE
MODULO IN ('PEDIDO_VENDAS')
--AND CHAVE IN (
--		'LJ00000448','LJ00000651'
--	)
AND DATA_INTEGRACAO >= '20250527'
order by 3 desc, 5 asc

/*
SELECT DISTINCT(MODULO) FROM MQ_LOG_INTEGRACAO_eCATALOGOS_LOJAS
MODULO
CORES
SEPARADOR
FILIAIS
ESTOQUE
CONFERENTES
VENDEDORES
CLIENTES
LOGIN
FATURAMENTO
CLIENTES PRIORITY
PEDIDOS_LOJA
IMAGENS
GERENTE
PEDIDO_VENDAS (eCatalogo para Linx)
PRODUTOS
TOKEN
*/

*/
