--Consulta do estoque, separado 25 produtos de grupos diferentes, de cada filial

WITH ProdutosFiltrados AS (
    SELECT
        A.PRODUTO AS REFERENCIA,
        A.COR_PRODUTO AS COR,
        G.DESC_PRODUTO,
        G.GRUPO_PRODUTO,
        G.SUBGRUPO_PRODUTO,
        A.DISPONIVEL,
        A.FILIAL,
        J.COD_FILIAL,
        ROW_NUMBER() OVER (
            PARTITION BY 
			G.SUBGRUPO_PRODUTO, --Adicionado o subgrupo para abranger mais referencias diferentes do mesmo grupo
			G.GRUPO_PRODUTO, 
			A.FILIAL
            ORDER BY A.DISPONIVEL DESC ) AS RN
    FROM MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
		INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS D
			ON A.PRODUTO = D.PRODUTO AND A.COR_PRODUTO = D.COR_PRODUTO
		INNER JOIN PRODUTOS_PRECOS AS E
			ON A.PRODUTO = E.PRODUTO AND E.CODIGO_TAB_PRECO = '03'
		INNER JOIN PRODUTOS_BARRA AS F
			ON A.PRODUTO = F.PRODUTO AND F.CODIGO_BARRA LIKE '7%'
		INNER JOIN PRODUTOS AS G
			ON A.PRODUTO = G.PRODUTO
		INNER JOIN FILIAIS AS J
			ON A.FILIAL = J.FILIAL
    WHERE 
        J.COD_FILIAL IN ('000043', '000015') -- Guarulhos e Joinville
        AND G.COLECAO IN ('55', '56')
),
ProdutosSelecionados AS (
    SELECT * FROM ProdutosFiltrados
    WHERE RN = 1
)
SELECT TOP 25 *
FROM ProdutosSelecionados
WHERE COD_FILIAL = '000043' -- Guarulhos

UNION ALL

SELECT TOP 25 *
FROM ProdutosSelecionados
WHERE COD_FILIAL = '000015' -- Joinville
ORDER BY FILIAL, REFERENCIA, GRUPO_PRODUTO

/*
--Script original

SELECT	
		A.PRODUTO			AS REFERENCIA, 
		A.COR_PRODUTO		AS COR, 
		G.DESC_PRODUTO, 
		G.GRUPO_PRODUTO, 
		G.SUBGRUPO_PRODUTO, 
		A.DISPONIVEL,
		A.FILIAL
FROM MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
	INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS D
			ON A.PRODUTO = D.PRODUTO 
				AND A.COR_PRODUTO = D.COR_PRODUTO
	INNER JOIN PRODUTOS_PRECOS AS E
			ON A.PRODUTO = E.PRODUTO
				AND E.CODIGO_TAB_PRECO = '03'
	INNER JOIN PRODUTOS_BARRA AS F
			ON A.PRODUTO = F.PRODUTO
				AND F.CODIGO_BARRA LIKE '7%'
	INNER JOIN PRODUTOS	AS G
			ON A.PRODUTO = G.PRODUTO
	--INNER JOIN PRODUTOS_TAMANHOS AS H
	--        ON G.GRADE = G.GRADE
	--INNER JOIN MQ_GRADE_PRODUCAO AS I
	--        ON A.PRODUTO = I.PRODUTO
	INNER JOIN FILIAIS AS J
			ON A.FILIAL = J.FILIAL
WHERE 
	J.COD_FILIAL IN ('000043', '000015') 
	AND A.DISPONIVEL >= D.QTDE
	AND G.COLECAO IN ('55', '56')
	--AND G.CONVERTR = 1
*/
