--Script de Consulta de Clientes

SELECT DISTINCT 
	B.COD_CLIFOR	AS COD_CLIENTE
	,B.RAZAO_SOCIAL	AS RAZAO_SOCIAL
	,B.NOME_CLIFOR	AS NOME_CLIENTE
	,CASE WHEN B.pj_pf = 1 THEN 'PJ' ELSE 'PF' END AS PF_PJ
	,TRIM(B.CGC_CPF) AS CNPJ_CPF
	,TRIM(B.RG_IE) AS RG_IE
	,F.ecatalogosloja AS ENVIA_ECATALOGO
	,CASE WHEN E.SEM_CREDITO = 1 THEN 'CREDITO INATIVO' ELSE 'CREDITO ATIVO' END AS POSSUI_CREDITO
	,TRIM(E.TIPO_BLOQUEIO) AS TIPO_BLOQUEIO
	,E.LIMITE_CREDITO
	,ISNULL(FORMAT(E.BLOQUEIO_FATURAMENTO, 'dd/MM/yyyy', 'pt-BR'),'SEM BLOQUEIO') AS BLOQ_FATURAMENTO 
	,ISNULL(FORMAT(E.BLOQUEIO_EXPEDICAO, 'dd/MM/yyyy', 'pt-BR'),'SEM BLOQUEIO') AS BLOQ_EXPEDICAO
	,ISNULL(FORMAT(E.BLOQUEIO_PEDIDOS, 'dd/MM/yyyy', 'pt-BR'),'SEM BLOQUEIO') AS BLOQ_PEDIDOS
	,ISNULL(A.vendedor,'0000') AS VENDEDOR
	,C.NOME_VENDEDOR
	--CAMPOS DA TABELA CADASTRO_CLI_FOR
	,B.NOME_CLIFOR
	,B.ENDERECO
	,B.NUMERO
	,B.BAIRRO
	,B.CEP
	,B.CIDADE
	,B.UF
	,B.EMAIL AS EMAIL
	,B.DDD1 + ' ' + B.TELEFONE1	AS DDD_TELEFONE
	,B.DDD1
	,B.TELEFONE1
	,B.DDD2
	,B.TELEFONE2
	,B.DDDFAX
	,B.FAX
	,CASE WHEN B.INATIVO = 1 THEN 'INATIVO' ELSE 'ATIVO' END	CLIENTE_ATIVO
FROM   MQ_CLIENTE_VENDEDOR AS A --Essa tabela MQ_CLIENTE_VENDEDOR valida o cliente vinculado ao vendedor no e-catalogo
	INNER JOIN CLIENTES_ATACADO AS F
		ON A.CLIENTE_ATACADO = F.CLIENTE_ATACADO
	INNER JOIN CADASTRO_CLI_FOR AS B
		ON A.CLIENTE_ATACADO = B.NOME_CLIFOR
	INNER JOIN LOJA_VENDEDORES AS C
		ON A.VENDEDOR = LTRIM(RTRIM(C.VENDEDOR))
	INNER JOIN CLIENTES_ATACADO AS E
		ON B.COD_CLIFOR = E.CLIFOR
WHERE  
	B.INATIVO = 0
	AND  F.eCatalogosLoja = 1
