------------------------------------------------------------------------
-----CONSULTA TABELA DE PRODUCAO - TEMPO AVANÇO FASE (DIAS) = 0.00------
------FILTRADO PARA TRAZER SOMENTE OPS COM TEMPO_OPERACAO = 0.00--------
------FILTRADO PARA TRAZER SOMENTE OPS COM FASE USADA NO SISPLAN--------
------------------------------------------------------------------------
SELECT
	 A.ORDEM_PRODUCAO
	,B.TAREFA
	,A.TABELA_OPERACOES AS COD_ROTA_PRODUCAO
	,C.DESCRICAO_TABELA AS DESC_ROTA_PRODUCAO
	,C.GRUPO_PRODUTO
	,B.TEMPO_OPERACAO AS TEMPO_AVANCO_FASE_DIAS
	,B.INICIO_LIBERADO
	,B.INICIO_REAL
	,B.FIM_ATUALIZADO
	,B.FIM_PREVISTO
	,B.ENCERRAMENTO
	,B.SEQUENCIA_PRODUTIVA
	,B.SEQUENCIA_ANTERIOR
	,B.FASE_PRODUCAO
	,A.STATUS AS STATUS_OP
	,B.STATUS AS STATUS_TAREFA
FROM
PRODUCAO_ORDEM A
	INNER JOIN PRODUCAO_TAREFAS B
		ON A.ORDEM_PRODUCAO = B.ORDEM_PRODUCAO
	INNER JOIN PRODUTOS_TAB_OPERACOES C
		ON A.TABELA_OPERACOES = C.TABELA_OPERACOES
	INNER JOIN PRODUCAO_FASE D
		ON D.FASE_PRODUCAO = B.FASE_PRODUCAO
WHERE 
A.STATUS <> 'E'					--OP COM STATUS DIFERENTE DE ENCERRADO
AND B.STATUS = 1				--TAREFA COM STATUS AGUARDANDO
AND B.TEMPO_OPERACAO = '0.00'	--SEM DIAS DE AVANÇO INFORMADO
AND A.EMISSAO >= '20250101'		--SOMENTE ANO CORRENTE
AND D.ENVIA_SISPLAN = 1			--SOMENTE FASES USADAS NO SISPLAN

--AND B.INICIO_REAL > B.FIM_ATUALIZADO
--AND A.ORDEM_PRODUCAO = '231091'
ORDER BY 1, 12

------------------------------------------------------------------------
--------------CONSULTA TABELA DE ROTAS DE OPERACOES---------------------
--FILTRADO PARA TRAZER AS ROTAS QUE ESTAO SEM TEMPO_OPERACAO DEFINIDO---
------------------------------------------------------------------------
SELECT 
	 A.TABELA_OPERACOES AS COD_ROTA_PRODUCAO
	,A.DESCRICAO_TABELA AS DESC_ROTA_PRODUCAO
	,A.GRUPO_PRODUTO
	,B.TEMPO_OPERACAO AS TEMPO_AVANCO_FASE_DIAS
	,B.FASE_PRODUCAO
	,B.SEQUENCIA_PRODUTIVA
	,B.SEQUENCIA_ANTERIOR
FROM PRODUTOS_TAB_OPERACOES A
	INNER JOIN PRODUTO_OPERACOES_ROTAS B
		ON A.TABELA_OPERACOES = B.TABELA_OPERACOES
	INNER JOIN PRODUCAO_FASE C
		ON C.FASE_PRODUCAO = B.FASE_PRODUCAO
WHERE
TEMPO_OPERACAO = '0.00'					--SEM DIAS DE AVANÇO INFORMADO 
AND A.DESCRICAO_TABELA LIKE '%GANG%'	--SOMENTE ROTAS COM FINAL - GANG
AND C.ENVIA_SISPLAN = 1					--SOMENTE FASES USADAS NO SISPLAN

--A.TABELA_OPERACOES = '178'
ORDER BY 1, 6

/*
------------------------------------------------------------------------
----------CONSULTA TABELA DE PRODUCAO - ERRO DIAS PRODUCAO = 0.00
-------------------TABELAS DE ORIGEM DO JOIN----------------------------
------------------------------------------------------------------------
SELECT
ORDEM_PRODUCAO
,INICIO_LIBERADO
,INICIO_REAL
,STATUS
,TABELA_OPERACOES
FROM
PRODUCAO_ORDEM
WHERE 
--STATUS <> E
ORDEM_PRODUCAO = '231091'

SELECT
ORDEM_PRODUCAO
,TAREFA
,SEQUENCIA_PRODUTIVA
,SEQUENCIA_ANTERIOR
,FASE_PRODUCAO
,INICIO_LIBERADO
,INICIO_REAL
,FIM_PREVISTO
,FIM_ATUALIZADO
,ENCERRAMENTO
,TEMPO_OPERACAO
,STATUS
FROM
PRODUCAO_TAREFAS
WHERE
ORDEM_PRODUCAO = '231091'
--STATUS <> 3
ORDER BY SEQUENCIA_PRODUTIVA --= '5905741'

------------------------------------------------------------------------
--------------CONSULTA TABELA DE ROTAS DE OPERACOES---------------------
-------------------TABELAS DE ORIGEM DO JOIN----------------------------
------------------------------------------------------------------------
SELECT 
	TABELA_OPERACOES
	,DESCRICAO_TABELA
	,GRUPO_PRODUTO
FROM PRODUTOS_TAB_OPERACOES
WHERE 
	TABELA_OPERACOES = '178'

SELECT 
	TABELA_OPERACOES
	,FASE_PRODUCAO
	,SEQUENCIA_PRODUTIVA
	,SEQUENCIA_ANTERIOR
	,TEMPO_OPERACAO
FROM PRODUTO_OPERACOES_ROTAS
WHERE 
	TABELA_OPERACOES = '178'
ORDER BY 
	SEQUENCIA_PRODUTIVA
*/
