--Script de Consulta de Clientes Utilizado no Integrador
--Os campos deste select são os campos obrigatórios a serem preenchidos no cadastro de clientes do Linx para que suba o cliente para o eCatalogo

SELECT DISTINCT 
	B.COD_CLIFOR	AS COD_CLIENTE
	,B.RAZAO_SOCIAL	AS RAZAO_SOCIAL
	,B.NOME_CLIFOR	AS NOME_CLIENTE
	,B.CGC_CPF	AS CNPJ_CPF
	,E.TIPO_BLOQUEIO
	,CASE WHEN E.SEM_CREDITO = 1 THEN 'CREDITO INATIVO' ELSE 'CREDITO ATIVO' END	AS POSSUI_CREDITO
	,E.LIMITE_CREDITO
	,E.BLOQUEIO_EXPEDICAO
	,E.BLOQUEIO_PEDIDOS
	,E.BLOQUEIO_FATURAMENTO
	,B.NOME_CLIFOR
	,B.ENDERECO
	,B.CIDADE
	,B.UF
	,B.BAIRRO
	,B.NUMERO
	,B.CEP
	,B.EMAIL	AS EMAIL
	,B.DDD1 + ' ' + B.TELEFONE1	AS DDD_TELEFONE
	,B.DDD1
	,B.TELEFONE1
	,B.DDD2
	,B.TELEFONE2
	,B.DDDFAX
	,B.FAX
	,D.ID
	,D.ACAO
	,CASE WHEN B.INATIVO = 1 THEN 'INATIVO' ELSE 'ATIVO' END	CLIENTE_ATIVO
FROM   MQ_CLIENTE_VENDEDOR AS A --Essa tabela MQ_CLIENTE_VENDEDOR valida o cliente vinculado ao vendedor no e-catalogo
	INNER JOIN CLIENTES_ATACADO AS F
		ON A.CLIENTE_ATACADO = F.CLIENTE_ATACADO
	INNER JOIN CADASTRO_CLI_FOR AS B
		ON A.CLIENTE_ATACADO = B.NOME_CLIFOR
	INNER JOIN LOJA_VENDEDORES AS C
		ON A.VENDEDOR = LTRIM(RTRIM(C.VENDEDOR))
	--Este JOIN na tabela MQ_INTEGRACAO_ECATALOGOS_LOJAS valida se o cliente está na fila de integração do e-catalogo. Se não retornar o cliente, não está para integrar.
	INNER JOIN MQ_INTEGRACAO_ECATALOGOS_LOJAS AS D
		ON B.CLIFOR = D.CHAVE
	INNER JOIN CLIENTES_ATACADO AS E
		ON B.COD_CLIFOR = E.CLIFOR
WHERE  
		 B.INATIVO = 0
	AND  D.MODULO = 'CLIENTES_PRIORITY'
	AND  F.eCatalogosLoja = 1
