----------------------------------------------------------------
--Ambiente Teste - Tabela de registro dos clientes da Convertr--
----------------Realizar de <> para com Linx--------------------
----------------------------------------------------------------

SELECT
	 NOME_CLIFOR		AS CLIENTES_ATACADO_CLIENTE_ATACADO
	,CGC_CPF			AS CLIENTES_ATACADO_CGC_CPF
	,RAZAO_SOCIAL		AS CADASTRO_CLI_FOR_RAZAO_SOCIAL
	,PJ_PF				AS CADASTRO_CLI_FOR_PJ_PF
	,RG_IE				AS CADASTRO_CLI_FOR_RG_IE
	,ENDERECO			AS CADASTRO_CLI_FOR_ENDERECO
	,NUMERO				AS CADASTRO_CLI_FOR_NUMERO
	,COMPLEMENTO		AS CADASTRO_CLI_FOR_COMPLEMENTO
	,BAIRRO				AS CADASTRO_CLI_FOR_BAIRRO
	,CIDADE				AS CADASTRO_CLI_FOR_CIDADE
	,UF					AS CADASTRO_CLI_FOR_UF
	,CEP				AS CADASTRO_CLI_FOR_CEP
	,PAIS				AS CADASTRO_CLI_FOR_PAIS
	,DDD1				AS CADASTRO_CLI_FOR_DDD1
	,TELEFONE1			AS CADASTRO_CLI_FOR_TELEFONE1
	,DDI				AS CADASTRO_CLI_FOR_DDI
	,CADASTRAMENTO		AS CADASTRO_CLI_FOR_CADASTRAMENTO
	,EMAIL				AS CADASTRO_CLI_FOR_EMAIL
	,HABILITAR_ATACADO	AS CADASTRO_CLI_FOR_INDICA_CLIENTE
	,OBSERVACAO			AS CLIENTES_ATACADO_OBS
FROM MQ_CLIENTE_TEMPORARIO
