--Relatorio de Clientes x Vendedor - 23MAI25
--Relatorio para analise de clientes que estão sem vendedor padrão cadastrado

SELECT
	TRIM(F.NOME_CLIFOR) AS CLIENTE
	,TRIM(F.FILIAL) AS FILIAL_FATURAMENTO
	,TRIM(F.NF_SAIDA) AS NF_SAIDA_FATURAMENTO
	,TRIM(F.SERIE_NF) AS SERIE_NF_FATURAMENTO
	,F.EMISSAO AS EMISSAO_FATURAMENTO
	--Retorna o vendedor referente à tabela de faturamento
	,TRIM(FV.VENDEDOR) AS COD_VENDEDOR_FATURAMENTO
	,TRIM(LV.NOME_VENDEDOR) AS NOME_VENDEDOR_FATURAMENTO
	--Retorna o vendedor referente à tabela de mq_cliente_vendedor
	,ISNULL(TRIM(MCV.VENDEDOR), '0000' ) AS COD_VENDEDOR_ATUAL
	,ISNULL(TRIM(LV2.NOME_VENDEDOR), 'CLIENTE SEM VENDEDOR PADRAO CADASTRADO') AS NOME_VENDEDOR_ATUAL 
	,ISNULL(TRIM(MCV.FILIAL), 'CLIENTE SEM FILIAL PADRAO CADASTRADA' ) AS FILIAL_VENDEDOR_ATUAL
	,ISNULL(TRIM(MGC.COD_GRUPO), '000' ) AS COD_GRUPO
	,ISNULL(TRIM(MGC.GRUPO_CLIENTE), 'CLIENTE SEM GRUPO' ) AS GRUPO_CLIENTE
FROM FATURAMENTO F
	INNER JOIN FATURAMENTO_VENDEDORES FV
		ON F.NF_SAIDA = FV.NF_SAIDA
			AND F.SERIE_NF = FV.SERIE_NF
			AND FV.VENDEDOR IS NOT NULL
			AND F.FILIAL = FV.FILIAL	
	--Retorna o vendedor referente à tabela de faturamento
	INNER JOIN LOJA_VENDEDORES LV
		ON FV.VENDEDOR = LV.VENDEDOR
	--Retorna o vendedor referente à tabela de mq_cliente_vendedor
	LEFT JOIN MQ_CLIENTE_VENDEDOR MCV
		ON MCV.CLIENTE_ATACADO = F.NOME_CLIFOR
			AND MCV.FILIAL = F.FILIAL
	LEFT JOIN LOJA_VENDEDORES LV2
		ON MCV.VENDEDOR = LV2.VENDEDOR
	LEFT JOIN MQ_GRUPO_CLIENTE_ITEM MGCI
		ON MGCI.CLIENTE_ATACADO = F.NOME_CLIFOR
	LEFT JOIN MQ_GRUPO_CLIENTE MGC
		ON MGC.COD_GRUPO = MGCI.COD_GRUPO
WHERE 
		F.FILIAL IN ('MAR QUENTE - FILIAL 08', 'MAR QUENTE - FILIAL 09', 'MAR QUENTE - GANGSTER')
	AND F.SERIE_NF IN ('E1', '51')
	AND F.EMISSAO BETWEEN '20240401' AND '20251231'
ORDER BY 
	TRIM(F.NOME_CLIFOR) ASC
	,TRIM(F.NF_SAIDA) DESC
	,F.EMISSAO DESC


/*****************************************************************************
Tabela necessárias:
Faturamento: filial, nf_saida, serie_nf
Faturamento_Vendedores: filial, nf_saida, serie_nf, cod_vendedor
Loja_Vendedores: cod_vendedor, nome_vendedor
MQ_Cliente_Vendedor: filial, cliente, cod_vendedor

Filtros:
vendedores <> NULL or ' '
filiais dixie (08) e gangster
periodo DEZ/24 - MAI/25


select NOME_CLIFOR AS F_NOME_CLIFOR, FILIAL AS F_FILIAL, NF_SAIDA AS F_NF_SAIDA, SERIE_NF AS F_SERIE_NF, EMISSAO AS F_EMISSAO from Faturamento F where FILIAL IN ('MAR QUENTE - FILIAL 08','MAR QUENTE - GANGSTER') AND SERIE_NF IN ('E1','51') AND EMISSAO BETWEEN '20250520' AND '20250523' ORDER BY nf_saida DESC -- AND nf_saida in ('000045','742276') 

select NF_SAIDA AS FV_NF_SAIDA, SERIE_NF AS FV_SERIE_NF, VENDEDOR AS FV_VENDEDOR, FILIAL AS FV_FILIAL from Faturamento_Vendedores FV where nf_saida in ('004363','204280','002003') AND SERIE_NF IN ('E1','51') AND VENDEDOR IS NOT NULL AND FILIAL = 'MAR QUENTE - FILIAL 08'

select CLIENTE_ATACADO AS MQC_CLIENTE_ATACADO, VENDEDOR AS MQC_VENDEDOR_ATUAL, FILIAL AS MQC_FILIAL, INATIVO AS MQC_INATIVO from MQ_Cliente_Vendedor MQC where CLIENTE_ATACADO IN (select NOME_CLIFOR from Faturamento F where FILIAL = 'MAR QUENTE - FILIAL 08' AND SERIE_NF IN ('E1','51') AND nome_clifor = 'DESTAK CONFECCOES')

select VENDEDOR AS LV_VENDEDOR, CODIGO_FILIAL AS LV_CODIGO_FILIAL, NOME_VENDEDOR AS LV_NOME_VENDEDOR, DATA_DESATIVACAO AS LV_DATA_DESATIVACAO from Loja_Vendedores LV where vendedor in (select VENDEDOR from Faturamento_Vendedores FV where nf_saida in ('004363','204280','002003') AND SERIE_NF IN ('E1','51') AND VENDEDOR IS NOT NULL AND FILIAL = 'MAR QUENTE - FILIAL 08')
*****************************************************************************/
