select distinct(tipo_bloqueio) from clientes_atacado

/*
TIPO_BLOQUEIO
_________________________
INATIVO PERMANENTE       
BOLETO BANCARIO VENCIDO  
BLOQUEIO AUTOMATICO      
ANALISE CREDITO PENDENTE 
PEDIDO SEPA SEM RETIRADA
CLIENTE BLOQ PERDA DADOS
FUNCIONARIO
INATIVO PERM PEND FINANC 
CHEQUE DEVOLVIDO
BLOQUEIO POR PDD         
ROMANEIO EM ABERTO
EM PROCESSO JURIDICO     
BLOQUEIO POR RENEGOCIACAO
LIBERADO                 
CLIENTE VIP              
FILIAL
SEM COMPRA + DE 6 MESES
CLIENTE REDE             
LIMITE EXCEDIDO          
*/
