--Valida Produto na Integração para INCLUSÃO

--NOT IN - Produtos que não estão cadastrados para inclusão, se aparecer vai ser atualizado
--Tirar o NOT da linha 39 - Fila para atualização

SELECT B.DESC_PRODUTO,
	   B.PRODUTO,
	   B.GRIFFE,
	   B.GRUPO_PRODUTO,
	   D.COD_FILIAL,
	   B.TIPO_PRODUTO,
	   B.DESC_PRODUTO,
	   ''       AS COMPOSITION,
	   ''       AS TECHNICAL_INFO,
	   B.CLASSIF_FISCAL,
	   E.DESC_COLECAO,
	   F.PRECO1,
	   G.CODIGO_BARRA,
	   A.DISPONIVEL,
	   H.QTDE
FROM   MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
	   INNER JOIN PRODUTOS AS B
			   ON A.PRODUTO = B.PRODUTO
	   INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS C
			   ON A.PRODUTO = C.PRODUTO
	   INNER JOIN FILIAIS AS D
			   ON A.FILIAL = D.FILIAL
				  AND D.ECATALOGOSLOJA = 1
	   INNER JOIN COLECOES AS E
			   ON B.COLECAO = E.COLECAO
	   INNER JOIN PRODUTOS_PRECOS AS F
			   ON B.PRODUTO = F.PRODUTO
				  AND F.CODIGO_TAB_PRECO = '01'
	   INNER JOIN PRODUTOS_BARRA AS G
			   ON B.PRODUTO = G.PRODUTO
				  AND G.CODIGO_BARRA LIKE '7%'
	   INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS H
			   ON B.PRODUTO = H.PRODUTO
WHERE  DISPONIVEL >= C.QTDE
  AND  B.PRODUTO NOT IN (SELECT PRODUTO FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS_PRODUTOS AS X 
						  WHERE X.PRODUTO = B.PRODUTO )
  AND  B.eCataLogosLoja = 1
  AND A.PRODUTO IN (
		'10.16.3915'
		,'29.09.0434'
		,'11.24.2286'
		,'10.16.2538'
		,'29.08.1329'
		,'11.24.2089'
		,'29.08.0919'
		,'11.24.3533'
		,'10.16.2977'
		,'10.16.2614'
		,'10.10.0122'
		,'11.24.3532'
		,'14.07.1129'
		,'14.11.0361'
		,'87.09.0257'
		,'11.24.3532'
		,'10.10.0122'
		,'14.07.1129'
	)
