--Valida as linhas onde os produtos estão duplicados na mesma filial

WITH CTE_PRODUTOS AS (
    SELECT
        D.COD_FILIAL,
        B.PRODUTO,
		A.COR_PRODUTO,
        G.CODIGO_BARRA
    FROM MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
		INNER JOIN PRODUTOS AS B 
			ON A.PRODUTO = B.PRODUTO
				AND B.PRODUTO IN (SELECT PRODUTO FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS_PRODUTOS AS X WHERE X.PRODUTO = B.PRODUTO)
				AND B.eCataLogosLoja = 1
		INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS C 
			ON A.PRODUTO = C.PRODUTO
				AND A.COR_PRODUTO = C.COR_PRODUTO 
		INNER JOIN FILIAIS AS D 
			ON A.FILIAL = D.FILIAL
				AND D.ECATALOGOSLOJA = 1
		INNER JOIN COLECOES AS E 
			ON B.COLECAO = E.COLECAO
		INNER JOIN PRODUTOS_PRECOS AS F 
			ON B.PRODUTO = F.PRODUTO
				AND F.CODIGO_TAB_PRECO = '01'
		INNER JOIN PRODUTOS_BARRA AS G 
			ON B.PRODUTO = G.PRODUTO
				AND G.CODIGO_BARRA_PADRAO = '1'
    WHERE A.DISPONIVEL >= C.QTDE
)
SELECT 
    PRODUTO,
    CODIGO_BARRA,
	COR_PRODUTO,
    COUNT(DISTINCT COD_FILIAL) AS QTD_FILIAIS,
    COUNT(*) AS TOTAL_LINHAS
FROM 
    CTE_PRODUTOS
GROUP BY 
    PRODUTO,
	COR_PRODUTO,
    CODIGO_BARRA
HAVING 
    COUNT(*) > COUNT(DISTINCT COD_FILIAL)
ORDER BY 
    PRODUTO

/*
--Consulta detalhada linha a linha por produto

WITH CTE_PRODUTOS AS (
    SELECT
        D.COD_FILIAL,
        B.PRODUTO,
		A.COR_PRODUTO,
        G.CODIGO_BARRA
    FROM MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
		INNER JOIN PRODUTOS AS B 
			ON A.PRODUTO = B.PRODUTO
				AND B.PRODUTO IN (SELECT PRODUTO FROM MQ_INTEGRACAO_eCATALOGOS_LOJAS_PRODUTOS AS X WHERE X.PRODUTO = B.PRODUTO)
			AND B.eCataLogosLoja = 1
		INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS C 
			ON A.PRODUTO = C.PRODUTO
				AND A.COR_PRODUTO = C.COR_PRODUTO 
		INNER JOIN FILIAIS AS D 
			ON A.FILIAL = D.FILIAL
				AND D.ECATALOGOSLOJA = 1
		INNER JOIN COLECOES AS E 
			ON B.COLECAO = E.COLECAO
		INNER JOIN PRODUTOS_PRECOS AS F 
			ON B.PRODUTO = F.PRODUTO
				AND F.CODIGO_TAB_PRECO = '01'
		INNER JOIN PRODUTOS_BARRA AS G 
			ON B.PRODUTO = G.PRODUTO
				AND G.CODIGO_BARRA_PADRAO = '1'
    WHERE A.DISPONIVEL >= C.QTDE
),
CTE_DUPLICADOS AS (
    SELECT 
        PRODUTO,
	COR_PRODUTO,
        CODIGO_BARRA
    FROM 
        CTE_PRODUTOS
    GROUP BY 
        PRODUTO,
	COR_PRODUTO,
        CODIGO_BARRA
    HAVING 
        COUNT(*) > COUNT(DISTINCT COD_FILIAL)
)
SELECT 
    P.COD_FILIAL,
    P.PRODUTO,
	P.COR_PRODUTO,
    P.CODIGO_BARRA
FROM 
    CTE_PRODUTOS AS P
INNER JOIN 
    CTE_DUPLICADOS AS D
    ON P.PRODUTO = D.PRODUTO
    AND P.CODIGO_BARRA = D.CODIGO_BARRA
ORDER BY 
    P.PRODUTO, 
	P.COR_PRODUTO,
    P.CODIGO_BARRA, 
    P.COD_FILIAL

*/
