--Verifica_Pedido_Duplicado_NaoFaturado_Linx

--VENDAS_PROD_EMBALADO = se o pedido constar aqui, NÃO está faturado
select distinct (PEDIDO) AS PEDIDO, * from VENDAS_PROD_EMBALADO where pedido IN (
'LA-01560528'
,'LA-01560363'
,'LA-01560529'
,'LA-01557019'
,'LA-01537496'
,'LA-01543500'
,'LA-01552259'
,'LA-01552657')


--Consulta JOIN VENDAS, FATURAMENTO_PROD E FATURAMENTO

select 
 TRIM(V.PEDIDO) AS V_PEDIDO
,TRIM(FP.PEDIDO) AS FP_PEDIDO
,TRIM(V.PEDIDO_EXTERNO) AS V_PEDIDO_EXTERNO
,TRIM(F.NF_SAIDA) AS F_NF_SAIDA
,TRIM(FP.NF_SAIDA) AS FP_NF_SAIDA
,TRIM(F.FATURA_NUMERO) AS F_FATURA_NUMERO
,TRIM(F.SERIE_NF) AS F_SERIE_NF
,TRIM(FP.SERIE_NF) AS FP_SERIE_NF
,TRIM(F.FATURA_SERIE) AS F_FATURA_SERIE
,TRIM(F.NATUREZA_SAIDA) AS F_NATUREZA_SAIDA
,TRIM(V.FILIAL) AS V_FILIAL
,TRIM(V.CLIENTE_ATACADO) AS V_CLIENTE_ATACADO
,TRIM(V.REPRESENTANTE) AS V_REPRESENTANTE
,V.FAT_ENVIADO_ECAT AS V_FAT_ENVIADO_ECAT
,V.EMISSAO AS V_EMISSAO
,F.EMISSAO AS F_EMISSAO
,V.DATA_PARA_TRANSFERENCIA AS V_DATA_PARA_TRANSFERENCIA
,F.DATA_PARA_TRANSFERENCIA AS F_DATA_PARA_TRANSFERENCIA
,V.CADASTRAMENTO AS V_CADASTRAMENTO
,V.DATA_ENVIO AS V_DATA_ENVIO
,V.DATA_RECEBIMENTO AS V_DATA_RECEBIMENTO
,F.DATA_HORA_EMISSAO AS F_DATA_HORA_EMISSAO
,F.DATA_SAIDA AS F_DATA_SAIDA
,F.NOTA_IMPRESSA AS F_NOTA_IMPRESSA
,F.NF_FATURA AS F_NF_FATURA
,V.TOT_QTDE_ORIGINAL AS V_TOT_QTDE_ORIGINAL
,V.TOT_QTDE_ENTREGUE AS V_TOT_QTDE_ENTREGUE
,V.TOT_QTDE_EMBALADA AS V_TOT_QTDE_EMBALADA
,V.TOT_QTDE_DEVOLVIDA AS V_TOT_QTDE_DEVOLVIDA
,V.TOT_QTDE_CANCELADA AS V_TOT_QTDE_CANCELADA
,V.TOT_QTDE_ENTREGAR AS V_TOT_QTDE_ENTREGAR
,V.TOT_VALOR_ORIGINAL AS V_TOT_VALOR_ORIGINAL
,V.TOT_VALOR_ENTREGUE AS V_TOT_VALOR_ENTREGUE
,V.TOT_VALOR_CANCELADO AS V_TOT_VALOR_CANCELADO
,V.TOT_VALOR_DEVOLVIDO AS V_TOT_VALOR_DEVOLVIDO
,V.TOT_VALOR_ENTREGAR AS V_TOT_VALOR_ENTREGAR
,V.TOT_BRUTO_ENTREGUE AS V_TOT_BRUTO_ENTREGUE
,F.QTDE_TOTAL AS F_QTDE_TOTAL
,F.MPADRAO_VALOR_TOTAL AS F_MPADRAO_VALOR_TOTAL
,F.MPADRAO_VALOR_SUB_ITENS AS F_MPADRAO_VALOR_SUB_ITENS
,F.MPADRAO_DESCONTO AS F_MPADRAO_DESCONTO
,F.MPADRAO_FRETE AS F_MPADRAO_FRETE
,F.VALOR_SUB_ITENS AS F_VALOR_SUB_ITENS
,F.VALOR_TOTAL AS F_VALOR_TOTAL
from VENDAS AS V
	INNER JOIN FATURAMENTO_PROD FP
		ON FP.PEDIDO = V.PEDIDO
	INNER JOIN FATURAMENTO F
		ON TRIM(F.NOME_CLIFOR) = TRIM(V.CLIENTE_ATACADO)
where V.pedido_externo in ('LJ00000844')
AND F.SERIE_NF = 'E1'
ORDER BY V.FAT_ENVIADO_ECAT desc, TRIM(V.PEDIDO_EXTERNO)

/******************************************************************
--Consulta Pedido tabela VENDAS
select 
TRIM(PEDIDO) AS PEDIDO_LINX
,TRIM(PEDIDO_EXTERNO) AS PEDIDO_ECAT
,DATA_ENVIO
,CODIGO_TAB_PRECO
,TIPO
,DATA_RECEBIMENTO
,CONDICAO_PGTO
,FILIAL
,CLIENTE_ATACADO
,TRANSPORTADORA
,REPRESENTANTE
,COMISSAO
,GERENTE
,COMISSAO_GERENTE
,EMISSAO
,CADASTRAMENTO
,TOT_QTDE_ORIGINAL
,TOT_QTDE_ENTREGUE
,TOT_QTDE_EMBALADA
,TOT_QTDE_DEVOLVIDA
,TOT_QTDE_CANCELADA
,TOT_QTDE_ENTREGAR
,TOT_VALOR_ORIGINAL
,TOT_VALOR_ENTREGUE
,TOT_VALOR_CANCELADO
,TOT_VALOR_DEVOLVIDO
,TOT_VALOR_ENTREGAR
,DESCONTO
,ENCARGO
,VALOR_IPI
,ACEITA_JUNTAR_PED
,OBS
,TOT_BRUTO_ENTREGUE
,TIPO_FRETE
,DATA_PARA_TRANSFERENCIA
,TOT_ENTREGUE_MOEDA_PADRAO
,PEDIDO_VENDA_ORIGEM
,FILIAL_DIGITACAO
,NOME_CLIFOR_ENTREGA
,DESCONTO_BRUTO
,DESCONTO_BRUTO_1
,DESCONTO_BRUTO_2
,DESCONTO_BRUTO_3
,DESCONTO_BRUTO_4
,VALOR_SUB_ITENS
,GUID
,ECATALOGOS
,CONCEITO_ECAT
,FAT_ENVIADO_ECAT
from VENDAS where pedido_externo in (
'LJ00000844'
,'LJ00000126'
,'LJ00000472'
,'LJ00001057'
)
ORDER BY TRIM(CLIENTE_ATACADO), FAT_ENVIADO_ECAT desc, TRIM(PEDIDO_EXTERNO)

******************************************************************
--Consulta Pedido Faturamento - verificar NFe
select 
FILIAL
,NF_SAIDA
,SERIE_NF
,NOME_CLIFOR
,NATUREZA_SAIDA
,TRANSPORTADORA
,TIPO_FRETE
,EMISSAO
,DATA_SAIDA
,VALOR_TOTAL
,QTDE_TOTAL
,NF_FATURA
,FATURA
,NOTA_IMPRESSA
,OBS
,VOLUMES
,TIPO_VOLUME
,NOTA_CANCELADA
,DEVOLUCAO
,REPRESENTANTE
,DESCONTO_BRUTO
,DATA_CANCELAMENTO
,VALOR_CANCELADO
,QTDE_CANCELADA
,DATA_HORA_EMISSAO
,DATA_PAGAMENTO
,AUTORIZACAO
from faturamento 
where 
NOME_CLIFOR in ('LOJAS FARINA P ALEGRE','MARIVALDA FERREIRA DOS AN','VITORIA F A S H I O N','OUZ MODAS')
--OUZ MODAS
AND FILIAL = 'MAR QUENTE - FILIAL 08'
--AND NF_SAIDA = '204382'
AND SERIE_NF = 'E1'
ORDER BY EMISSAO DESC

******************************************************************

select * from FATURAMENTO_PROD where pedido in (
'LA-01560528'
,'LA-01560363'
,'LA-01560529'
,'LA-01557019'
,'LA-01537496'
,'LA-01543500'
,'LA-01552259'
,'LA-01552657')

********************************************************************/
