USE [mar_quente]
GO

/****** Object:  View [dbo].[MQ_ESTOQUE_PRODUTOS_CONVERTR]    Script Date: 15/07/2025 08:28:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE OR ALTER   VIEW [dbo].[MQ_ESTOQUE_PRODUTOS_CONVERTR]
AS 

-- 18-04-25 - DANIEL BERNARDO - CRIAÇÃO DA VIEW
-- 23/05/25 - Adelmo - Adicionado Filtro para enviar somente produtos com campo CONVERTR = 1
-- 14/07/25 - Luiz Felipe - Adicionado filtro para separar os produtos nacionais e importados (tribut_origem)

SELECT	A.PRODUTO			AS REFERENCIA, 
		A.COR_PRODUTO		AS COR, 
		A.DISPONIVEL,
		A.FILIAL
FROM MQ_ESTOQUE_DISPONIVEL_PEDIDO_NEW AS A
INNER JOIN PRODUTOS_PACKS_PERMITIDOS AS D
        ON A.PRODUTO = D.PRODUTO AND A.COR_PRODUTO = D.COR_PRODUTO
INNER JOIN PRODUTOS_PRECOS AS E
        ON A.PRODUTO = E.PRODUTO
            AND E.CODIGO_TAB_PRECO = '03'
INNER JOIN PRODUTOS_BARRA AS F
        ON A.PRODUTO = F.PRODUTO
            AND F.CODIGO_BARRA LIKE '7%'
INNER JOIN PRODUTOS	AS G
		ON A.PRODUTO = G.PRODUTO
--INNER JOIN PRODUTOS_TAMANHOS AS H
--        ON G.GRADE = G.GRADE
--INNER JOIN MQ_GRADE_PRODUCAO AS I
--        ON A.PRODUTO = I.PRODUTO
INNER JOIN FILIAIS AS J
		ON A.FILIAL = J.FILIAL
WHERE J.COD_FILIAL IN ('000043', '000015') 
AND A.DISPONIVEL >= D.QTDE
AND G.CONVERTR = 1
AND (
        (A.FILIAL = 'MAR QUENTE - FILIAL 06' AND G.TRIBUT_ORIGEM = '0')
     OR (A.FILIAL = 'JOINVILLE' AND G.TRIBUT_ORIGEM IN ('1', '2'))
  )



GO
